[package]
name = "dasol"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
ariadne = { version = "0.4.1", features = ["auto-color"] }
pest = { version = "2.7.11", features = ["pretty-print"] }
pest_derive = "2.7.11"
